### PR TITLE
Fixes #44 by relaxing validations for some commands

### LINKED ISSUE #44: version command: missing ~/.ankh/config
after a fresh install, running `ankh version` prints this error:

```
$ ankh version
# WARNING /Users/ogupte/.ankh/config: Unable to read ankh config '/Users/ogupte/.ankh/config': open /Users/ogupte/.ankh/config: no such file or directory
# ERROR   Context '' not found in `contexts`
# INFO    The following contexts are available:
```

### PR DESCRIPTION
**Pull request by jondlm**

### CODE REVIEW

File: ankh/main.go [hunk 1]
```diff
@@ -426,7 +426,7 @@ func main() {
 		if ctx.ContextOverride != "" {
 			mergedAnkhConfig.CurrentContextName = ctx.ContextOverride
 		}
-		if ctx.Environment == "" {
+		if ctx.Environment == "" && !ctx.IgnoreConfigError {
```
Comment (jondlm) [inline ankh/main.go]: Not sure if this was the right approach, but it seems to work.

File: ankh/main.go [hunk 2]
```diff
@@ -702,6 +702,7 @@ func main() {
 
 	app.Command("version", "Show version info", func(cmd *cli.Cmd) {
 		ctx.WarnOnConfigError = true
+		ctx.IgnoreConfigError = true
```
Comment (jondlm) [inline ankh/main.go]: Also just make `ankh version` ignore config errors
